/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_HEX_BRIDGE_TYPES_PB_H_INCLUDED
#define PB_HEX_BRIDGE_TYPES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MsgSourceType {
    /* 永远不要主动使用这个值 */
    MsgSourceType_SOURCE_UNKNOWN = 0,
    /* 外网 CAN. 如果设备只有一个 CAN, 则定义为外网 CAN */
    MsgSourceType_SOURCE_EXTERNAL_CAN = 1,
    /* 内网 CAN */
    MsgSourceType_SOURCE_INTERNAL_CAN = 2,
    /* ROS, 实际一般指 自动化的代码 发送的 CAN 消息,
 与 XVIEW 这种 用户操作 的消息区分开来 */
    MsgSourceType_SOURCE_PC_ROS = 3,
    /* XVIEW, 实际一般指 用户操作 的软件 发送的 CAN 消息, */
    MsgSourceType_SOURCE_XVIEW = 4,
    /* 特殊 Source,
 为 HexStdCanMsg.source 时指 CAN-HUB 自己发出的消息
 为 HexStdCanMsg.destination 时指专门发给 CAN-HUB 的消息,
  CAN-HUB收到后将不会转发到物理CAN线等其他消息源上 */
    MsgSourceType_SOURCE_CAN_HUB = 6
} MsgSourceType;

typedef enum _DeviceClass {
    DeviceClass_OTHER_DEVICE = 0,
    DeviceClass_ESP_CAN_HUB = 1,
    DeviceClass_PC = 2,
    DeviceClass_ROUTER_CAN_HUB = 3
} DeviceClass;

typedef enum _HexBridgeProtocolVersion {
    HexBridgeProtocolVersion_HexBridgeProtocolInvalid = 0,
    HexBridgeProtocolVersion_HexBridgeProtocolV1 = 1
} HexBridgeProtocolVersion;

/* Struct definitions */
typedef struct _MonotonicClock {
    uint32_t ms_since_system_boot;
} MonotonicClock;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MsgSourceType_MIN MsgSourceType_SOURCE_UNKNOWN
#define _MsgSourceType_MAX MsgSourceType_SOURCE_CAN_HUB
#define _MsgSourceType_ARRAYSIZE ((MsgSourceType)(MsgSourceType_SOURCE_CAN_HUB+1))

#define _DeviceClass_MIN DeviceClass_OTHER_DEVICE
#define _DeviceClass_MAX DeviceClass_ROUTER_CAN_HUB
#define _DeviceClass_ARRAYSIZE ((DeviceClass)(DeviceClass_ROUTER_CAN_HUB+1))

#define _HexBridgeProtocolVersion_MIN HexBridgeProtocolVersion_HexBridgeProtocolInvalid
#define _HexBridgeProtocolVersion_MAX HexBridgeProtocolVersion_HexBridgeProtocolV1
#define _HexBridgeProtocolVersion_ARRAYSIZE ((HexBridgeProtocolVersion)(HexBridgeProtocolVersion_HexBridgeProtocolV1+1))



/* Initializer values for message structs */
#define MonotonicClock_init_default              {0}
#define MonotonicClock_init_zero                 {0}

/* Field tags (for use in manual encoding/decoding) */
#define MonotonicClock_ms_since_system_boot_tag  1

/* Struct field encoding specification for nanopb */
#define MonotonicClock_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ms_since_system_boot,   1)
#define MonotonicClock_CALLBACK NULL
#define MonotonicClock_DEFAULT NULL

extern const pb_msgdesc_t MonotonicClock_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MonotonicClock_fields &MonotonicClock_msg

/* Maximum encoded size of messages (where known) */
#define HEX_BRIDGE_TYPES_PB_H_MAX_SIZE           MonotonicClock_size
#define MonotonicClock_size                      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
