/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_HEX_BRIDGE_PB_H_INCLUDED
#define PB_HEX_BRIDGE_PB_H_INCLUDED
#include <pb.h>
#include "hexstd_can_msg.pb.h"
#include "hex_bridge_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RTCTimestamp {
    /* Represents seconds of UTC time since Unix epoch
 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
 9999-12-31T23:59:59Z inclusive. */
    uint32_t seconds;
    uint32_t micro_seconds;
} RTCTimestamp;

typedef struct _DeviceInfo {
    DeviceClass device_class;
    bool can_ext_id_capable;
    bool can_fd_capable;
    /* Max len 8(Include null terminator), usually git hash */
    bool has_version;
    char version[8];
} DeviceInfo;

typedef struct _DeviceConfig {
    /* Name of this device, not version of type
 Use it like this:
  Kison's HUB
 Max len 25(Include null terminator) */
    bool has_name;
    char name[25];
    /* 自身的 HEX-STD CAN ID, 注意范围不是0-0xFF
 是 0x xx xx xx 00
 带有 CLASS 与 TYPE 信息, FUNC 部分留空为 00 */
    bool has_can_full_id;
    uint32_t can_full_id;
} DeviceConfig;

typedef struct _MessageSourceInfo {
    MsgSourceType type;
    bool available;
} MessageSourceInfo;

typedef struct _MessageSourceConfig {
    MsgSourceType type;
    uint32_t baud_rate;
    bool enabled;
    uint32_t filter_id;
    uint32_t filter_mask;
} MessageSourceConfig;

typedef struct _Property {
    pb_size_t which_prop;
    union {
        /* readonly */
        DeviceInfo info;
        /* readwrite */
        DeviceConfig config;
        /* readonly */
        MessageSourceInfo msg_source_info;
        /* readwrite */
        MessageSourceConfig msg_source_config;
        /* readwrite */
        RTCTimestamp time;
        /* readonly */
        MonotonicClock monotonic_clock;
    } prop;
} Property;

typedef struct _Bridge {
    HexBridgeProtocolVersion protocol_version;
    pb_size_t which_msg;
    union {
        HexStdCanMsg can_msg;
        Property property_request;
        Property property_response;
        Property set_property;
        /* Check if someone is there */
        uint32_t ping;
        /* Send back same value when receiving a ping */
        uint32_t pong;
        /* When set to true, RX should reboot or do equivalent thing */
        bool reboot;
    } msg;
} Bridge;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define RTCTimestamp_init_default                {0, 0}
#define DeviceInfo_init_default                  {_DeviceClass_MIN, 0, 0, false, ""}
#define DeviceConfig_init_default                {false, "", false, 0}
#define MessageSourceInfo_init_default           {_MsgSourceType_MIN, 0}
#define MessageSourceConfig_init_default         {_MsgSourceType_MIN, 0, 0, 0, 0}
#define Property_init_default                    {0, {DeviceInfo_init_default}}
#define Bridge_init_default                      {_HexBridgeProtocolVersion_MIN, 0, {HexStdCanMsg_init_default}}
#define RTCTimestamp_init_zero                   {0, 0}
#define DeviceInfo_init_zero                     {_DeviceClass_MIN, 0, 0, false, ""}
#define DeviceConfig_init_zero                   {false, "", false, 0}
#define MessageSourceInfo_init_zero              {_MsgSourceType_MIN, 0}
#define MessageSourceConfig_init_zero            {_MsgSourceType_MIN, 0, 0, 0, 0}
#define Property_init_zero                       {0, {DeviceInfo_init_zero}}
#define Bridge_init_zero                         {_HexBridgeProtocolVersion_MIN, 0, {HexStdCanMsg_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define RTCTimestamp_seconds_tag                 1
#define RTCTimestamp_micro_seconds_tag           2
#define DeviceInfo_device_class_tag              1
#define DeviceInfo_can_ext_id_capable_tag        2
#define DeviceInfo_can_fd_capable_tag            3
#define DeviceInfo_version_tag                   4
#define DeviceConfig_name_tag                    1
#define DeviceConfig_can_full_id_tag             2
#define MessageSourceInfo_type_tag               1
#define MessageSourceInfo_available_tag          2
#define MessageSourceConfig_type_tag             1
#define MessageSourceConfig_baud_rate_tag        2
#define MessageSourceConfig_enabled_tag          3
#define MessageSourceConfig_filter_id_tag        4
#define MessageSourceConfig_filter_mask_tag      5
#define Property_info_tag                        1
#define Property_config_tag                      2
#define Property_msg_source_info_tag             3
#define Property_msg_source_config_tag           4
#define Property_time_tag                        5
#define Property_monotonic_clock_tag             6
#define Bridge_protocol_version_tag              1
#define Bridge_can_msg_tag                       2
#define Bridge_property_request_tag              3
#define Bridge_property_response_tag             4
#define Bridge_set_property_tag                  5
#define Bridge_ping_tag                          6
#define Bridge_pong_tag                          7
#define Bridge_reboot_tag                        8

/* Struct field encoding specification for nanopb */
#define RTCTimestamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seconds,           1) \
X(a, STATIC,   SINGULAR, UINT32,   micro_seconds,     2)
#define RTCTimestamp_CALLBACK NULL
#define RTCTimestamp_DEFAULT NULL

#define DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    device_class,      1) \
X(a, STATIC,   SINGULAR, BOOL,     can_ext_id_capable,   2) \
X(a, STATIC,   SINGULAR, BOOL,     can_fd_capable,    3) \
X(a, STATIC,   OPTIONAL, STRING,   version,           4)
#define DeviceInfo_CALLBACK NULL
#define DeviceInfo_DEFAULT NULL

#define DeviceConfig_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   name,              1) \
X(a, STATIC,   OPTIONAL, UINT32,   can_full_id,       2)
#define DeviceConfig_CALLBACK NULL
#define DeviceConfig_DEFAULT NULL

#define MessageSourceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, BOOL,     available,         2)
#define MessageSourceInfo_CALLBACK NULL
#define MessageSourceInfo_DEFAULT NULL

#define MessageSourceConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   baud_rate,         2) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           3) \
X(a, STATIC,   SINGULAR, UINT32,   filter_id,         4) \
X(a, STATIC,   SINGULAR, UINT32,   filter_mask,       5)
#define MessageSourceConfig_CALLBACK NULL
#define MessageSourceConfig_DEFAULT NULL

#define Property_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (prop,info,prop.info),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (prop,config,prop.config),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (prop,msg_source_info,prop.msg_source_info),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (prop,msg_source_config,prop.msg_source_config),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (prop,time,prop.time),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (prop,monotonic_clock,prop.monotonic_clock),   6)
#define Property_CALLBACK NULL
#define Property_DEFAULT NULL
#define Property_prop_info_MSGTYPE DeviceInfo
#define Property_prop_config_MSGTYPE DeviceConfig
#define Property_prop_msg_source_info_MSGTYPE MessageSourceInfo
#define Property_prop_msg_source_config_MSGTYPE MessageSourceConfig
#define Property_prop_time_MSGTYPE RTCTimestamp
#define Property_prop_monotonic_clock_MSGTYPE MonotonicClock

#define Bridge_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    protocol_version,   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,can_msg,msg.can_msg),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,property_request,msg.property_request),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,property_response,msg.property_response),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,set_property,msg.set_property),   5) \
X(a, STATIC,   ONEOF,    UINT32,   (msg,ping,msg.ping),   6) \
X(a, STATIC,   ONEOF,    UINT32,   (msg,pong,msg.pong),   7) \
X(a, STATIC,   ONEOF,    BOOL,     (msg,reboot,msg.reboot),   8)
#define Bridge_CALLBACK NULL
#define Bridge_DEFAULT NULL
#define Bridge_msg_can_msg_MSGTYPE HexStdCanMsg
#define Bridge_msg_property_request_MSGTYPE Property
#define Bridge_msg_property_response_MSGTYPE Property
#define Bridge_msg_set_property_MSGTYPE Property

extern const pb_msgdesc_t RTCTimestamp_msg;
extern const pb_msgdesc_t DeviceInfo_msg;
extern const pb_msgdesc_t DeviceConfig_msg;
extern const pb_msgdesc_t MessageSourceInfo_msg;
extern const pb_msgdesc_t MessageSourceConfig_msg;
extern const pb_msgdesc_t Property_msg;
extern const pb_msgdesc_t Bridge_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RTCTimestamp_fields &RTCTimestamp_msg
#define DeviceInfo_fields &DeviceInfo_msg
#define DeviceConfig_fields &DeviceConfig_msg
#define MessageSourceInfo_fields &MessageSourceInfo_msg
#define MessageSourceConfig_fields &MessageSourceConfig_msg
#define Property_fields &Property_msg
#define Bridge_fields &Bridge_msg

/* Maximum encoded size of messages (where known) */
#define Bridge_size                              38
#define DeviceConfig_size                        32
#define DeviceInfo_size                          15
#define HEX_BRIDGE_PB_H_MAX_SIZE                 Bridge_size
#define MessageSourceConfig_size                 22
#define MessageSourceInfo_size                   4
#define Property_size                            34
#define RTCTimestamp_size                        12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
