/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_HEXSTD_CAN_MSG_PB_H_INCLUDED
#define PB_HEXSTD_CAN_MSG_PB_H_INCLUDED
#include <pb.h>
#include "hex_bridge_types.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(8) HexStdCanMsg_data_t;
typedef struct _HexStdCanMsg {
    uint32_t id;
    /* 为了方便 nanopb 处理, 在 options 中指定 data 最长长度为 8
 关于兼容 CAN-FD, 利用协议版本号区分一下吧 */
    HexStdCanMsg_data_t data;
    /* True 代表此 frame 是 can 扩展帧 */
    bool ext_id;
    /* True 代表此 frame 是 fd can 帧.
 如果设备不支持 can 帧, 此帧既不会被转发, 也不会被记录 */
    bool can_fd;
    /* 自身发出收到的CAN消息时加上 source
 PC 发给 CAN HUB 时 **应该** 使用以下值.
  SOURCE_PC_ROS
  SOURCE_XVIEW
 PC 发给 CAN HUB 时 **禁止** 使用以下值. 使用以下值会导致此包被丢弃
  SOURCE_CAN_HUB
  SOURCE_EXTERNAL_CAN
  SOURCE_INTERNAL_CAN
 为了向后兼容, 如果 CAN HUB 收到其他值的消息,
 会将 source 改为 SOURCE_UNKNOWN,
 发送 SOURCE_UNKNOWN 的行为将与 SOURCE_PC_ROS 的行为保持一致 */
    MsgSourceType source;
    /* 希望本消息被发送到哪里, 留空代表发送到设备默认
 PC 发给 CAN HUB 时只 **允许** 以下值. 其他任何值会导致此包被丢弃
  留空(发送到设备自身默认)
  SOURCE_EXTERNAL_CAN
  SOURCE_INTERNAL_CAN
  SOURCE_CAN_HUB
 CAN HUB 外发时不会使用此值 */
    bool has_destination;
    MsgSourceType destination;
    /* 接收时间戳 */
    bool has_receive_time;
    MonotonicClock receive_time;
} HexStdCanMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define HexStdCanMsg_init_default                {0, {0, {0}}, 0, 0, _MsgSourceType_MIN, false, _MsgSourceType_MIN, false, MonotonicClock_init_default}
#define HexStdCanMsg_init_zero                   {0, {0, {0}}, 0, 0, _MsgSourceType_MIN, false, _MsgSourceType_MIN, false, MonotonicClock_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define HexStdCanMsg_id_tag                      1
#define HexStdCanMsg_data_tag                    2
#define HexStdCanMsg_ext_id_tag                  3
#define HexStdCanMsg_can_fd_tag                  4
#define HexStdCanMsg_source_tag                  5
#define HexStdCanMsg_destination_tag             6
#define HexStdCanMsg_receive_time_tag            7

/* Struct field encoding specification for nanopb */
#define HexStdCanMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2) \
X(a, STATIC,   SINGULAR, BOOL,     ext_id,            3) \
X(a, STATIC,   SINGULAR, BOOL,     can_fd,            4) \
X(a, STATIC,   SINGULAR, UENUM,    source,            5) \
X(a, STATIC,   OPTIONAL, UENUM,    destination,       6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  receive_time,      7)
#define HexStdCanMsg_CALLBACK NULL
#define HexStdCanMsg_DEFAULT NULL
#define HexStdCanMsg_receive_time_MSGTYPE MonotonicClock

extern const pb_msgdesc_t HexStdCanMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HexStdCanMsg_fields &HexStdCanMsg_msg

/* Maximum encoded size of messages (where known) */
#define HEXSTD_CAN_MSG_PB_H_MAX_SIZE             HexStdCanMsg_size
#define HexStdCanMsg_size                        32

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
