/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "hex_bridge.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RTCTimestamp, RTCTimestamp, AUTO)


PB_BIND(DeviceInfo, DeviceInfo, AUTO)


PB_BIND(DeviceConfig, DeviceConfig, AUTO)


PB_BIND(MessageSourceInfo, MessageSourceInfo, AUTO)


PB_BIND(MessageSourceConfig, MessageSourceConfig, AUTO)


PB_BIND(Property, Property, AUTO)


PB_BIND(Bridge, Bridge, AUTO)



